### ISSUE TITLE
Use NLB and not CLB

### ISSUE THREAD

**Issue by ArtiomL** [sorinboia/nginx-experience-aws#9]
The configuration of your load balancer is controlled by annotations that are added to the manifest for your service. By default, Classic Load Balancers are used for LoadBalancer type services. To use the Network Load Balancer instead, apply the following annotation to your service:

```
service.beta.kubernetes.io/aws-load-balancer-type: nlb
```

**Comment by sorinboia** [comment]
Done in api gateway deployment
